sudo: required
language: python

branches:
  only:
    - travisfix

matrix:
  include:
    - python: '2.7'
    - python: '3.4'
    - python: '3.5'
    - python: '3.6'
    - dist: trusty
      services:
        - docker
      script:
        - ./make/manylinux1/build_wheels.sh
    - os: osx
      osx_image: xcode9.4
      script:
        - ./make/osx/build_wheels.sh

install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then ./make/osx/install_python.sh; fi
