sudo: required
services:
  - docker

branches:
  only:
    - travisfix

matrix:
  include:
    - python: '2.7'
      dist: trusty
    - python: '3.4'
      dist: trusty
    - python: '3.5'
      dist: trusty
    - python: '3.6'
      dist: trusty

    - os: osx
      osx_image: xcode9.4

script:
  - if [ "${TRAVIS_OS_NAME:-}" == "linux" ]; then ./make/manylinux1/build_wheels.sh; fi
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then ./make/osx/build_wheels.sh; fi

install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then ./make/osx/install_python.sh; fi
