sudo: required
language: python

branches:
  only:
    - travisfix

matrix:
  include:
    - dist: trusty
      python: '2.7'
      python: '3.4'
      python: '3.5'
      python: '3.6'
      services:
        - docker
    - os: osx
      osx_image: xcode9.4
      python: '2.7'
      python: '3.4'
      python: '3.5'
      python: '3.6'

script:
  - if [ "${TRAVIS_OS_NAME:-}" == "linux" ]; then ./make/manylinux1/build_wheels.sh; fi
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then ./make/osx/build_wheels.sh; fi

install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then ./make/osx/install_python.sh; fi
